<?php

defined('BASEPATH') OR exit('No direct script access allowed');



class Coba extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
        // $this->load->model('user_model');
        // $this->isLoggedIn();
        // $this->load->model('Absensi_model');
        $this->load->library('form_validation');
        $this->load->helper('url','date','form');

    }

    public function index()
    {
         $this->load->view('bbb');
    }

    public function daftarUserBaru()
    {
      $this->load->helper('url','form');
    $this->load->library('form_validation');
    $this->form_validation->set_rules('nama', 'nama', 'trim|required');

    $this->load->model('Pelanggan_model');
    if ($this->form_validation->run()==false)
    {
      //$this->load->view('boot');
      $this->load->view('cus/cus_view_daftar');
    }
    else
    {

        $this->Pelanggan_model->insertUser();
        $this->load->view('cus/cus_view_masuk');

    }

    }

    public function loginUser()
    {
      $this->load->view('cus/cus_view_login');
    }

            public function cekLoginCus()
          	{
          		$this->load->helper('url','form');
          		$this->load->library('form_validation');
          		$this->form_validation->set_rules('nama','nama','trim|required');
          		$this->form_validation->set_rules('password','password','trim|required|callback_cekDb');
          		if ($this->form_validation->run() == FALSE)
          		{

          			$this->load->view('cus/cus_view_login');
          		} else
          		{
          			$this->load->view('cus/homeCus');
          		}
          	}

          	public function cekDb($password)
          	{
          		$this->load->model('Pelanggan_model');
          		$nama = $this->input->post('nama');
          		$result = $this->Pelanggan_model->loginCus($nama,$password);
          		if($result)
          		{
          			$sess_array=array();
          			foreach ($result as $row )
          			{
          				$sess_array=array('id_pel'=>$row->id_pel,'nama'=>$row->nama);
          				$this->session->set_userdata('logged_in',$sess_array);
          			}
          			return true;
          		}
          		else
          		{
          			$this->form_validation->set_message('cekDb',"Login Gagal Username dan Password tidak valid");
          			return false;
          		}
          	}

          	public function logout()
          	{
          		$this->session->unset_userdata('logged_in');
          		$this->session->sess_destroy();
          		redirect('Coba','refresh');
          	}
}

/* End of file Absensi.php */
/* Location: ./application/controllers/Absensi.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-27 03:25:50 */
/* http://harviacode.com */
