<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Penjualan_model extends CI_Model
{

    public $table = 'penjualan';
    public $id = 'id_transaksi';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    function tampiljual()
    {
      $query = $this->db->query("SELECT * FROM jual");
      return $query->result();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }

    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_transaksi', $q);
	$this->db->or_like('idPelanggan', $q);
	$this->db->or_like('NamaBarang', $q);
	$this->db->or_like('JumlahSatuan', $q);
	$this->db->or_like('hargaSatuan', $q);
	$this->db->or_like('totalPenjualan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_transaksi', $q);
	$this->db->or_like('idPelanggan', $q);
	$this->db->or_like('NamaBarang', $q);
	$this->db->or_like('JumlahSatuan', $q);
	$this->db->or_like('hargaSatuan', $q);
	$this->db->or_like('totalPenjualan', $q);
	$this->db->or_like('tanggal', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }
    public function totalJual()
    {
      // $this->db->select('SUM(harga) as totJual');
      // $this->db->from('jual');

      $query = $this->db->query("SELECT SUM(harga) as totJual FROM jual");
      return $query->result();

    }

    public function totalbahan()
    {
      $query = $this->db->query("SELECT * FROM bahanbaku");
      return $query->result();

    }



}

/* End of file Penjualan_model.php */
/* Location: ./application/models/Penjualan_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-06-27 03:27:07 */
/* http://harviacode.com */
